-- Generated by flatten-openalex-jsonl.py --print-schema.
CREATE SCHEMA IF NOT EXISTS openalex;

DROP TABLE IF EXISTS openalex.authors CASCADE;
CREATE TABLE openalex.authors (
    id text,
    display_name text,
    full_name text,
    orcid text,
    display_name_alternatives jsonb,
    raw_author_names jsonb,
    works_count integer,
    cited_by_count integer,
    summary_2yr_mean_citedness double precision,
    summary_h_index integer,
    summary_i10_index integer,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.authors_ids CASCADE;
CREATE TABLE openalex.authors_ids (
    author_id text,
    openalex text,
    orcid text,
    scopus text
);

DROP TABLE IF EXISTS openalex.authors_counts_by_year CASCADE;
CREATE TABLE openalex.authors_counts_by_year (
    author_id text,
    year integer,
    works_count integer,
    cited_by_count integer,
    oa_works_count integer
);

DROP TABLE IF EXISTS openalex.authors_affiliations CASCADE;
CREATE TABLE openalex.authors_affiliations (
    author_id text,
    affiliation_position integer,
    institution_id text,
    institution_ror text,
    institution_display_name text,
    institution_country_code text,
    institution_type text,
    institution_lineage jsonb,
    years jsonb
);

DROP TABLE IF EXISTS openalex.authors_last_known_institutions CASCADE;
CREATE TABLE openalex.authors_last_known_institutions (
    author_id text,
    institution_position integer,
    institution_id text,
    institution_ror text,
    institution_display_name text,
    institution_country_code text,
    institution_type text,
    institution_lineage jsonb
);

DROP TABLE IF EXISTS openalex.authors_topics CASCADE;
CREATE TABLE openalex.authors_topics (
    author_id text,
    topic_position integer,
    topic_id text,
    display_name text,
    count integer,
    subfield_id text,
    subfield_display_name text,
    field_id text,
    field_display_name text,
    domain_id text,
    domain_display_name text
);

DROP TABLE IF EXISTS openalex.authors_topic_share CASCADE;
CREATE TABLE openalex.authors_topic_share (
    author_id text,
    topic_position integer,
    topic_id text,
    display_name text,
    value double precision,
    subfield_id text,
    subfield_display_name text,
    field_id text,
    field_display_name text,
    domain_id text,
    domain_display_name text
);

DROP TABLE IF EXISTS openalex.authors_x_concepts CASCADE;
CREATE TABLE openalex.authors_x_concepts (
    author_id text,
    concept_position integer,
    concept_id text,
    wikidata text,
    display_name text,
    level integer,
    score double precision,
    count integer
);

DROP TABLE IF EXISTS openalex.authors_sources CASCADE;
CREATE TABLE openalex.authors_sources (
    author_id text,
    source_position integer,
    source_id text,
    display_name text,
    issn_l text,
    issn jsonb,
    is_oa boolean,
    is_in_doaj boolean,
    is_core boolean,
    host_organization text,
    host_organization_name text,
    host_organization_lineage jsonb,
    host_organization_lineage_names jsonb,
    type text
);

DROP TABLE IF EXISTS openalex.awards CASCADE;
CREATE TABLE openalex.awards (
    id text,
    display_name text,
    description text,
    doi text,
    funder_id text,
    funder_display_name text,
    funder_ror text,
    funder_doi text,
    funder_award_id text,
    funder_scheme text,
    funding_type text,
    amount double precision,
    currency text,
    start_date date,
    start_year integer,
    end_date date,
    end_year integer,
    landing_page_url text,
    provenance text,
    funded_outputs_count integer,
    primary_topic_id text,
    primary_topic_display_name text,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.awards_funded_outputs CASCADE;
CREATE TABLE openalex.awards_funded_outputs (
    award_id text,
    output_position integer,
    work_id text
);

DROP TABLE IF EXISTS openalex.awards_investigators CASCADE;
CREATE TABLE openalex.awards_investigators (
    award_id text,
    investigator_position integer,
    investigator_role text,
    given_name text,
    family_name text,
    orcid text,
    role_start text,
    affiliation jsonb
);

DROP TABLE IF EXISTS openalex.awards_institutions CASCADE;
CREATE TABLE openalex.awards_institutions (
    award_id text,
    institution_position integer,
    institution_id text,
    institution_display_name text,
    institution_ror text,
    country_code text,
    raw_institution jsonb
);

DROP TABLE IF EXISTS openalex.awards_topics CASCADE;
CREATE TABLE openalex.awards_topics (
    award_id text,
    topic_position integer,
    topic_id text,
    display_name text,
    score double precision,
    subfield_id text,
    subfield_display_name text,
    field_id text,
    field_display_name text,
    domain_id text,
    domain_display_name text
);

DROP TABLE IF EXISTS openalex.concepts CASCADE;
CREATE TABLE openalex.concepts (
    id text,
    wikidata text,
    display_name text,
    level integer,
    description text,
    works_count integer,
    cited_by_count integer,
    summary_2yr_mean_citedness double precision,
    summary_h_index integer,
    summary_i10_index integer,
    image_url text,
    image_thumbnail_url text,
    international jsonb,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.concepts_ids CASCADE;
CREATE TABLE openalex.concepts_ids (
    concept_id text,
    openalex text,
    wikidata text,
    wikipedia text,
    umls_aui jsonb,
    umls_cui jsonb,
    mag text
);

DROP TABLE IF EXISTS openalex.concepts_ancestors CASCADE;
CREATE TABLE openalex.concepts_ancestors (
    concept_id text,
    ancestor_position integer,
    ancestor_id text,
    ancestor_display_name text
);

DROP TABLE IF EXISTS openalex.concepts_related_concepts CASCADE;
CREATE TABLE openalex.concepts_related_concepts (
    concept_id text,
    related_position integer,
    related_concept_id text,
    related_display_name text,
    score double precision
);

DROP TABLE IF EXISTS openalex.concepts_counts_by_year CASCADE;
CREATE TABLE openalex.concepts_counts_by_year (
    concept_id text,
    year integer,
    works_count integer,
    cited_by_count integer,
    oa_works_count integer
);

DROP TABLE IF EXISTS openalex.continents CASCADE;
CREATE TABLE openalex.continents (
    id text,
    display_name text,
    description text,
    display_name_alternatives jsonb,
    wikidata_id text,
    wikidata_url text,
    wikipedia_url text,
    ids jsonb,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.continents_countries CASCADE;
CREATE TABLE openalex.continents_countries (
    continent_id text,
    country_position integer,
    country_id text,
    country_display_name text
);

DROP TABLE IF EXISTS openalex.countries CASCADE;
CREATE TABLE openalex.countries (
    id text,
    display_name text,
    full_name text,
    description text,
    country_code text,
    alpha_3 text,
    numeric integer,
    continent_id text,
    continent_display_name text,
    is_global_south boolean,
    works_count integer,
    cited_by_count integer,
    works_api_url text,
    authors_api_url text,
    institutions_api_url text,
    display_name_alternatives jsonb,
    ids jsonb,
    wikidata_url text,
    wikipedia_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.domains CASCADE;
CREATE TABLE openalex.domains (
    id text,
    display_name text,
    description text,
    works_count integer,
    cited_by_count integer,
    display_name_alternatives jsonb,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.domains_ids CASCADE;
CREATE TABLE openalex.domains_ids (
    domain_id text,
    openalex text,
    wikidata text,
    wikipedia text
);

DROP TABLE IF EXISTS openalex.domains_fields CASCADE;
CREATE TABLE openalex.domains_fields (
    domain_id text,
    field_position integer,
    field_id text,
    field_display_name text
);

DROP TABLE IF EXISTS openalex.domains_siblings CASCADE;
CREATE TABLE openalex.domains_siblings (
    domain_id text,
    sibling_position integer,
    sibling_id text,
    sibling_display_name text
);

DROP TABLE IF EXISTS openalex.fields CASCADE;
CREATE TABLE openalex.fields (
    id text,
    display_name text,
    description text,
    domain_id text,
    domain_display_name text,
    works_count integer,
    cited_by_count integer,
    display_name_alternatives jsonb,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.fields_ids CASCADE;
CREATE TABLE openalex.fields_ids (
    field_id text,
    openalex text,
    wikidata text,
    wikipedia text
);

DROP TABLE IF EXISTS openalex.fields_subfields CASCADE;
CREATE TABLE openalex.fields_subfields (
    field_id text,
    subfield_position integer,
    subfield_id text,
    subfield_display_name text
);

DROP TABLE IF EXISTS openalex.fields_siblings CASCADE;
CREATE TABLE openalex.fields_siblings (
    field_id text,
    sibling_position integer,
    sibling_id text,
    sibling_display_name text
);

DROP TABLE IF EXISTS openalex.funders CASCADE;
CREATE TABLE openalex.funders (
    id text,
    display_name text,
    description text,
    country_code text,
    homepage_url text,
    image_url text,
    image_thumbnail_url text,
    alternate_titles jsonb,
    works_count integer,
    cited_by_count integer,
    awards_count integer,
    summary_2yr_mean_citedness double precision,
    summary_h_index integer,
    summary_i10_index integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.funders_ids CASCADE;
CREATE TABLE openalex.funders_ids (
    funder_id text,
    openalex text,
    ror text,
    wikidata text,
    doi text,
    crossref text
);

DROP TABLE IF EXISTS openalex.funders_counts_by_year CASCADE;
CREATE TABLE openalex.funders_counts_by_year (
    funder_id text,
    year integer,
    works_count integer,
    cited_by_count integer,
    oa_works_count integer
);

DROP TABLE IF EXISTS openalex.funders_roles CASCADE;
CREATE TABLE openalex.funders_roles (
    funder_id text,
    role_position integer,
    role text,
    role_id text,
    works_count integer
);

DROP TABLE IF EXISTS openalex.institution_types CASCADE;
CREATE TABLE openalex.institution_types (
    id text,
    display_name text,
    works_count integer,
    cited_by_count integer,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.institutions CASCADE;
CREATE TABLE openalex.institutions (
    id text,
    ror text,
    display_name text,
    country_code text,
    type text,
    type_id text,
    status text,
    homepage_url text,
    image_url text,
    image_thumbnail_url text,
    display_name_acronyms jsonb,
    display_name_alternatives jsonb,
    lineage jsonb,
    is_super_system boolean,
    works_count integer,
    cited_by_count integer,
    summary_2yr_mean_citedness double precision,
    summary_h_index integer,
    summary_i10_index integer,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.institutions_ids CASCADE;
CREATE TABLE openalex.institutions_ids (
    institution_id text,
    openalex text,
    ror text,
    grid text,
    wikipedia text,
    wikidata text,
    mag text
);

DROP TABLE IF EXISTS openalex.institutions_geo CASCADE;
CREATE TABLE openalex.institutions_geo (
    institution_id text,
    city text,
    geonames_city_id text,
    region text,
    country_code text,
    country text,
    latitude double precision,
    longitude double precision
);

DROP TABLE IF EXISTS openalex.institutions_associated_institutions CASCADE;
CREATE TABLE openalex.institutions_associated_institutions (
    institution_id text,
    associated_position integer,
    associated_institution_id text,
    associated_display_name text,
    relationship text
);

DROP TABLE IF EXISTS openalex.institutions_counts_by_year CASCADE;
CREATE TABLE openalex.institutions_counts_by_year (
    institution_id text,
    year integer,
    works_count integer,
    cited_by_count integer,
    oa_works_count integer
);

DROP TABLE IF EXISTS openalex.institutions_roles CASCADE;
CREATE TABLE openalex.institutions_roles (
    institution_id text,
    role_position integer,
    role text,
    role_id text,
    works_count integer
);

DROP TABLE IF EXISTS openalex.institutions_repositories CASCADE;
CREATE TABLE openalex.institutions_repositories (
    institution_id text,
    repository_position integer,
    repository_id text,
    repository_display_name text,
    host_organization text,
    host_organization_lineage jsonb,
    raw_repository jsonb
);

DROP TABLE IF EXISTS openalex.institutions_topics CASCADE;
CREATE TABLE openalex.institutions_topics (
    institution_id text,
    topic_position integer,
    topic_id text,
    display_name text,
    score double precision,
    count integer,
    subfield_id text,
    subfield_display_name text,
    field_id text,
    field_display_name text,
    domain_id text,
    domain_display_name text
);

DROP TABLE IF EXISTS openalex.institutions_topic_share CASCADE;
CREATE TABLE openalex.institutions_topic_share (
    institution_id text,
    topic_position integer,
    topic_id text,
    display_name text,
    value double precision,
    subfield_id text,
    subfield_display_name text,
    field_id text,
    field_display_name text,
    domain_id text,
    domain_display_name text
);

DROP TABLE IF EXISTS openalex.keywords CASCADE;
CREATE TABLE openalex.keywords (
    id text,
    display_name text,
    works_count integer,
    cited_by_count integer,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.languages CASCADE;
CREATE TABLE openalex.languages (
    id text,
    display_name text,
    works_count integer,
    cited_by_count bigint,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.licenses CASCADE;
CREATE TABLE openalex.licenses (
    id text,
    display_name text,
    description text,
    url text,
    works_count integer,
    cited_by_count integer,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.publishers CASCADE;
CREATE TABLE openalex.publishers (
    id text,
    display_name text,
    alternate_titles jsonb,
    country_codes jsonb,
    hierarchy_level integer,
    parent_publisher text,
    lineage jsonb,
    ror_id text,
    wikidata_id text,
    homepage_url text,
    image_url text,
    image_thumbnail_url text,
    works_count integer,
    cited_by_count integer,
    summary_2yr_mean_citedness double precision,
    summary_h_index integer,
    summary_i10_index integer,
    sources_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.publishers_ids CASCADE;
CREATE TABLE openalex.publishers_ids (
    publisher_id text,
    openalex text,
    ror text,
    wikidata text
);

DROP TABLE IF EXISTS openalex.publishers_counts_by_year CASCADE;
CREATE TABLE openalex.publishers_counts_by_year (
    publisher_id text,
    year integer,
    works_count integer,
    cited_by_count integer,
    oa_works_count integer
);

DROP TABLE IF EXISTS openalex.publishers_roles CASCADE;
CREATE TABLE openalex.publishers_roles (
    publisher_id text,
    role_position integer,
    role text,
    role_id text,
    works_count integer
);

DROP TABLE IF EXISTS openalex.sdgs CASCADE;
CREATE TABLE openalex.sdgs (
    id text,
    display_name text,
    description text,
    image_url text,
    image_thumbnail_url text,
    works_count integer,
    cited_by_count integer,
    ids jsonb,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.source_types CASCADE;
CREATE TABLE openalex.source_types (
    id text,
    display_name text,
    works_count integer,
    cited_by_count bigint,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.sources CASCADE;
CREATE TABLE openalex.sources (
    id text,
    issn_l text,
    issn jsonb,
    display_name text,
    alternate_titles jsonb,
    country_code text,
    type text,
    publisher text,
    host_organization text,
    host_organization_name text,
    host_organization_lineage jsonb,
    works_count integer,
    cited_by_count integer,
    oa_works_count integer,
    is_oa boolean,
    is_in_doaj boolean,
    is_core boolean,
    is_ojs boolean,
    is_in_scielo boolean,
    is_high_oa_rate boolean,
    is_high_oa_rate_since_year integer,
    is_in_doaj_since_year integer,
    first_publication_year integer,
    last_publication_year integer,
    oa_flip_year integer,
    apc_usd integer,
    summary_2yr_mean_citedness double precision,
    summary_h_index integer,
    summary_i10_index integer,
    homepage_url text,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.sources_ids CASCADE;
CREATE TABLE openalex.sources_ids (
    source_id text,
    openalex text,
    issn_l text,
    issn jsonb,
    mag text,
    wikidata text,
    fatcat text
);

DROP TABLE IF EXISTS openalex.sources_counts_by_year CASCADE;
CREATE TABLE openalex.sources_counts_by_year (
    source_id text,
    year integer,
    works_count integer,
    cited_by_count integer,
    oa_works_count integer
);

DROP TABLE IF EXISTS openalex.sources_apc_prices CASCADE;
CREATE TABLE openalex.sources_apc_prices (
    source_id text,
    price_position integer,
    price integer,
    currency text
);

DROP TABLE IF EXISTS openalex.sources_topics CASCADE;
CREATE TABLE openalex.sources_topics (
    source_id text,
    topic_position integer,
    topic_id text,
    display_name text,
    score double precision,
    count integer,
    subfield_id text,
    subfield_display_name text,
    field_id text,
    field_display_name text,
    domain_id text,
    domain_display_name text
);

DROP TABLE IF EXISTS openalex.sources_topic_share CASCADE;
CREATE TABLE openalex.sources_topic_share (
    source_id text,
    topic_position integer,
    topic_id text,
    display_name text,
    value double precision,
    subfield_id text,
    subfield_display_name text,
    field_id text,
    field_display_name text,
    domain_id text,
    domain_display_name text
);

DROP TABLE IF EXISTS openalex.subfields CASCADE;
CREATE TABLE openalex.subfields (
    id text,
    display_name text,
    description text,
    field_id text,
    field_display_name text,
    domain_id text,
    domain_display_name text,
    works_count integer,
    cited_by_count integer,
    display_name_alternatives jsonb,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.subfields_ids CASCADE;
CREATE TABLE openalex.subfields_ids (
    subfield_id text,
    openalex text,
    wikidata text,
    wikipedia text
);

DROP TABLE IF EXISTS openalex.subfields_topics CASCADE;
CREATE TABLE openalex.subfields_topics (
    subfield_id text,
    topic_position integer,
    topic_id text,
    topic_display_name text
);

DROP TABLE IF EXISTS openalex.subfields_siblings CASCADE;
CREATE TABLE openalex.subfields_siblings (
    subfield_id text,
    sibling_position integer,
    sibling_id text,
    sibling_display_name text
);

DROP TABLE IF EXISTS openalex.topics CASCADE;
CREATE TABLE openalex.topics (
    id text,
    display_name text,
    description text,
    keywords jsonb,
    subfield_id text,
    subfield_display_name text,
    field_id text,
    field_display_name text,
    domain_id text,
    domain_display_name text,
    works_count integer,
    cited_by_count integer,
    wikipedia_id text,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.topics_ids CASCADE;
CREATE TABLE openalex.topics_ids (
    topic_id text,
    openalex text,
    wikipedia text
);

DROP TABLE IF EXISTS openalex.topics_keywords CASCADE;
CREATE TABLE openalex.topics_keywords (
    topic_id text,
    keyword_position integer,
    keyword text
);

DROP TABLE IF EXISTS openalex.topics_siblings CASCADE;
CREATE TABLE openalex.topics_siblings (
    topic_id text,
    sibling_position integer,
    sibling_id text,
    sibling_display_name text
);

DROP TABLE IF EXISTS openalex.work_types CASCADE;
CREATE TABLE openalex.work_types (
    id text,
    display_name text,
    description text,
    works_count integer,
    cited_by_count bigint,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.works CASCADE;
CREATE TABLE openalex.works (
    id text,
    doi text,
    title text,
    display_name text,
    publication_year integer,
    publication_date date,
    language text,
    type text,
    authors_count integer,
    cited_by_count integer,
    referenced_works_count integer,
    locations_count integer,
    countries_distinct_count integer,
    institutions_distinct_count integer,
    fwci double precision,
    is_retracted boolean,
    is_paratext boolean,
    is_xpac boolean,
    has_fulltext boolean,
    has_content_pdf boolean,
    has_content_grobid_xml boolean,
    primary_topic_id text,
    primary_topic_display_name text,
    primary_topic_score double precision,
    primary_topic_subfield_id text,
    primary_topic_subfield_display_name text,
    primary_topic_field_id text,
    primary_topic_field_display_name text,
    primary_topic_domain_id text,
    primary_topic_domain_display_name text,
    abstract_inverted_index jsonb,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.works_ids CASCADE;
CREATE TABLE openalex.works_ids (
    work_id text,
    openalex text,
    doi text,
    mag text,
    pmid text,
    pmcid text
);

DROP TABLE IF EXISTS openalex.works_indexed_in CASCADE;
CREATE TABLE openalex.works_indexed_in (
    work_id text,
    position integer,
    indexed_in text
);

DROP TABLE IF EXISTS openalex.works_corresponding_author_ids CASCADE;
CREATE TABLE openalex.works_corresponding_author_ids (
    work_id text,
    position integer,
    author_id text
);

DROP TABLE IF EXISTS openalex.works_corresponding_institution_ids CASCADE;
CREATE TABLE openalex.works_corresponding_institution_ids (
    work_id text,
    position integer,
    institution_id text
);

DROP TABLE IF EXISTS openalex.works_primary_locations CASCADE;
CREATE TABLE openalex.works_primary_locations (
    work_id text,
    location_position integer,
    location_id text,
    source_id text,
    source_display_name text,
    source_issn_l text,
    source_issn jsonb,
    source_is_oa boolean,
    source_is_in_doaj boolean,
    source_is_core boolean,
    source_host_organization text,
    source_host_organization_name text,
    source_host_organization_lineage jsonb,
    source_host_organization_lineage_names jsonb,
    source_type text,
    is_oa boolean,
    is_published boolean,
    is_accepted boolean,
    landing_page_url text,
    pdf_url text,
    raw_source_name text,
    raw_type text,
    provenance text,
    license text,
    license_id text,
    version text
);

DROP TABLE IF EXISTS openalex.works_locations CASCADE;
CREATE TABLE openalex.works_locations (
    work_id text,
    location_position integer,
    location_id text,
    source_id text,
    source_display_name text,
    source_issn_l text,
    source_issn jsonb,
    source_is_oa boolean,
    source_is_in_doaj boolean,
    source_is_core boolean,
    source_host_organization text,
    source_host_organization_name text,
    source_host_organization_lineage jsonb,
    source_host_organization_lineage_names jsonb,
    source_type text,
    is_oa boolean,
    is_published boolean,
    is_accepted boolean,
    landing_page_url text,
    pdf_url text,
    raw_source_name text,
    raw_type text,
    provenance text,
    license text,
    license_id text,
    version text
);

DROP TABLE IF EXISTS openalex.works_best_oa_locations CASCADE;
CREATE TABLE openalex.works_best_oa_locations (
    work_id text,
    location_position integer,
    location_id text,
    source_id text,
    source_display_name text,
    source_issn_l text,
    source_issn jsonb,
    source_is_oa boolean,
    source_is_in_doaj boolean,
    source_is_core boolean,
    source_host_organization text,
    source_host_organization_name text,
    source_host_organization_lineage jsonb,
    source_host_organization_lineage_names jsonb,
    source_type text,
    is_oa boolean,
    is_published boolean,
    is_accepted boolean,
    landing_page_url text,
    pdf_url text,
    raw_source_name text,
    raw_type text,
    provenance text,
    license text,
    license_id text,
    version text
);

DROP TABLE IF EXISTS openalex.works_authorships CASCADE;
CREATE TABLE openalex.works_authorships (
    work_id text,
    authorship_position integer,
    author_position text,
    author_id text,
    author_display_name text,
    author_orcid text,
    raw_author_name text,
    raw_orcid text,
    is_corresponding boolean,
    countries jsonb
);

DROP TABLE IF EXISTS openalex.works_authorship_institutions CASCADE;
CREATE TABLE openalex.works_authorship_institutions (
    work_id text,
    authorship_position integer,
    institution_position integer,
    author_id text,
    institution_id text,
    institution_ror text,
    institution_display_name text,
    institution_country_code text,
    institution_type text,
    institution_lineage jsonb
);

DROP TABLE IF EXISTS openalex.works_authorship_affiliations CASCADE;
CREATE TABLE openalex.works_authorship_affiliations (
    work_id text,
    authorship_position integer,
    affiliation_position integer,
    raw_affiliation_string text,
    institution_ids jsonb,
    raw_affiliation jsonb
);

DROP TABLE IF EXISTS openalex.works_authorship_raw_affiliation_strings CASCADE;
CREATE TABLE openalex.works_authorship_raw_affiliation_strings (
    work_id text,
    authorship_position integer,
    raw_affiliation_position integer,
    raw_affiliation_string text
);

DROP TABLE IF EXISTS openalex.works_authorship_countries CASCADE;
CREATE TABLE openalex.works_authorship_countries (
    work_id text,
    authorship_position integer,
    country_position integer,
    country_code text
);

DROP TABLE IF EXISTS openalex.works_biblio CASCADE;
CREATE TABLE openalex.works_biblio (
    work_id text,
    volume text,
    issue text,
    first_page text,
    last_page text
);

DROP TABLE IF EXISTS openalex.works_topics CASCADE;
CREATE TABLE openalex.works_topics (
    work_id text,
    topic_position integer,
    topic_id text,
    display_name text,
    score double precision,
    subfield_id text,
    subfield_display_name text,
    field_id text,
    field_display_name text,
    domain_id text,
    domain_display_name text
);

DROP TABLE IF EXISTS openalex.works_keywords CASCADE;
CREATE TABLE openalex.works_keywords (
    work_id text,
    keyword_position integer,
    keyword_id text,
    display_name text,
    score double precision
);

DROP TABLE IF EXISTS openalex.works_concepts CASCADE;
CREATE TABLE openalex.works_concepts (
    work_id text,
    concept_position integer,
    concept_id text,
    wikidata text,
    display_name text,
    level integer,
    score double precision
);

DROP TABLE IF EXISTS openalex.works_sustainable_development_goals CASCADE;
CREATE TABLE openalex.works_sustainable_development_goals (
    work_id text,
    sdg_position integer,
    sdg_id text,
    display_name text,
    score double precision
);

DROP TABLE IF EXISTS openalex.works_awards CASCADE;
CREATE TABLE openalex.works_awards (
    work_id text,
    award_position integer,
    award_id text,
    display_name text,
    funder_award_id text,
    funder_id text,
    funder_display_name text
);

DROP TABLE IF EXISTS openalex.works_funders CASCADE;
CREATE TABLE openalex.works_funders (
    work_id text,
    funder_position integer,
    funder_id text,
    display_name text,
    ror text
);

DROP TABLE IF EXISTS openalex.works_institutions CASCADE;
CREATE TABLE openalex.works_institutions (
    work_id text,
    institution_position integer,
    institution_id text,
    institution_ror text,
    institution_display_name text,
    institution_country_code text,
    institution_type text,
    institution_lineage jsonb
);

DROP TABLE IF EXISTS openalex.works_open_access CASCADE;
CREATE TABLE openalex.works_open_access (
    work_id text,
    is_oa boolean,
    oa_status text,
    oa_url text,
    any_repository_has_fulltext boolean
);

DROP TABLE IF EXISTS openalex.works_counts_by_year CASCADE;
CREATE TABLE openalex.works_counts_by_year (
    work_id text,
    year integer,
    cited_by_count integer
);

DROP TABLE IF EXISTS openalex.works_citation_normalized_percentile CASCADE;
CREATE TABLE openalex.works_citation_normalized_percentile (
    work_id text,
    value double precision,
    is_in_top_1_percent boolean,
    is_in_top_10_percent boolean
);

DROP TABLE IF EXISTS openalex.works_cited_by_percentile_year CASCADE;
CREATE TABLE openalex.works_cited_by_percentile_year (
    work_id text,
    min integer,
    max integer
);

DROP TABLE IF EXISTS openalex.works_apc_list CASCADE;
CREATE TABLE openalex.works_apc_list (
    work_id text,
    value double precision,
    currency text,
    value_usd double precision,
    provenance text
);

DROP TABLE IF EXISTS openalex.works_apc_paid CASCADE;
CREATE TABLE openalex.works_apc_paid (
    work_id text,
    value double precision,
    currency text,
    value_usd double precision,
    provenance text
);

DROP TABLE IF EXISTS openalex.works_mesh CASCADE;
CREATE TABLE openalex.works_mesh (
    work_id text,
    mesh_position integer,
    descriptor_ui text,
    descriptor_name text,
    qualifier_ui text,
    qualifier_name text,
    is_major_topic boolean
);

DROP TABLE IF EXISTS openalex.works_referenced_works CASCADE;
CREATE TABLE openalex.works_referenced_works (
    work_id text,
    referenced_position integer,
    referenced_work_id text
);

DROP TABLE IF EXISTS openalex.works_related_works CASCADE;
CREATE TABLE openalex.works_related_works (
    work_id text,
    related_position integer,
    related_work_id text
);
