-- Generated by flatten-openalex-jsonl.py --print-schema --profile core --id-mode numeric.
CREATE SCHEMA IF NOT EXISTS openalex;

DROP TABLE IF EXISTS openalex.authors CASCADE;
CREATE TABLE openalex.authors (
    author_key bigint,
    id text,
    display_name text,
    full_name text,
    orcid text,
    works_count integer,
    cited_by_count integer,
    summary_2yr_mean_citedness double precision,
    summary_h_index integer,
    summary_i10_index integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.authors_ids CASCADE;
CREATE TABLE openalex.authors_ids (
    author_key bigint,
    openalex text,
    orcid text,
    scopus text
);

DROP TABLE IF EXISTS openalex.authors_last_known_institutions CASCADE;
CREATE TABLE openalex.authors_last_known_institutions (
    author_key bigint,
    institution_position integer,
    institution_key bigint,
    institution_country_code text
);

DROP TABLE IF EXISTS openalex.awards CASCADE;
CREATE TABLE openalex.awards (
    id text,
    display_name text,
    doi text,
    funder_key bigint,
    funder_display_name text,
    funder_ror text,
    funder_doi text,
    funder_award_id text,
    funder_scheme text,
    funding_type text,
    amount double precision,
    currency text,
    start_date date,
    start_year integer,
    end_date date,
    end_year integer,
    funded_outputs_count integer,
    primary_topic_key bigint,
    primary_topic_display_name text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.awards_funded_outputs CASCADE;
CREATE TABLE openalex.awards_funded_outputs (
    award_id text,
    output_position integer,
    work_key bigint
);

DROP TABLE IF EXISTS openalex.concepts CASCADE;
CREATE TABLE openalex.concepts (
    concept_key bigint,
    id text,
    wikidata text,
    display_name text,
    level integer,
    works_count integer,
    cited_by_count integer,
    summary_2yr_mean_citedness double precision,
    summary_h_index integer,
    summary_i10_index integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.concepts_ids CASCADE;
CREATE TABLE openalex.concepts_ids (
    concept_key bigint,
    openalex text,
    wikidata text,
    wikipedia text,
    umls_aui jsonb,
    umls_cui jsonb,
    mag text
);

DROP TABLE IF EXISTS openalex.continents CASCADE;
CREATE TABLE openalex.continents (
    id text,
    display_name text,
    description text,
    display_name_alternatives jsonb,
    wikidata_id text,
    wikidata_url text,
    wikipedia_url text,
    ids jsonb,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.continents_countries CASCADE;
CREATE TABLE openalex.continents_countries (
    continent_id text,
    country_position integer,
    country_id text,
    country_display_name text
);

DROP TABLE IF EXISTS openalex.countries CASCADE;
CREATE TABLE openalex.countries (
    id text,
    display_name text,
    full_name text,
    description text,
    country_code text,
    alpha_3 text,
    numeric integer,
    continent_id text,
    continent_display_name text,
    is_global_south boolean,
    works_count integer,
    cited_by_count integer,
    works_api_url text,
    authors_api_url text,
    institutions_api_url text,
    display_name_alternatives jsonb,
    ids jsonb,
    wikidata_url text,
    wikipedia_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.domains CASCADE;
CREATE TABLE openalex.domains (
    domain_key bigint,
    id text,
    display_name text,
    description text,
    works_count integer,
    cited_by_count integer,
    display_name_alternatives jsonb,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.domains_ids CASCADE;
CREATE TABLE openalex.domains_ids (
    domain_key bigint,
    openalex text,
    wikidata text,
    wikipedia text
);

DROP TABLE IF EXISTS openalex.domains_fields CASCADE;
CREATE TABLE openalex.domains_fields (
    domain_key bigint,
    field_position integer,
    field_key bigint,
    field_display_name text
);

DROP TABLE IF EXISTS openalex.domains_siblings CASCADE;
CREATE TABLE openalex.domains_siblings (
    domain_key bigint,
    sibling_position integer,
    sibling_id text,
    sibling_display_name text
);

DROP TABLE IF EXISTS openalex.fields CASCADE;
CREATE TABLE openalex.fields (
    field_key bigint,
    id text,
    display_name text,
    description text,
    domain_key bigint,
    domain_display_name text,
    works_count integer,
    cited_by_count integer,
    display_name_alternatives jsonb,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.fields_ids CASCADE;
CREATE TABLE openalex.fields_ids (
    field_key bigint,
    openalex text,
    wikidata text,
    wikipedia text
);

DROP TABLE IF EXISTS openalex.fields_subfields CASCADE;
CREATE TABLE openalex.fields_subfields (
    field_key bigint,
    subfield_position integer,
    subfield_key bigint,
    subfield_display_name text
);

DROP TABLE IF EXISTS openalex.fields_siblings CASCADE;
CREATE TABLE openalex.fields_siblings (
    field_key bigint,
    sibling_position integer,
    sibling_id text,
    sibling_display_name text
);

DROP TABLE IF EXISTS openalex.funders CASCADE;
CREATE TABLE openalex.funders (
    funder_key bigint,
    id text,
    display_name text,
    country_code text,
    works_count integer,
    cited_by_count integer,
    awards_count integer,
    summary_2yr_mean_citedness double precision,
    summary_h_index integer,
    summary_i10_index integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.funders_ids CASCADE;
CREATE TABLE openalex.funders_ids (
    funder_key bigint,
    openalex text,
    ror text,
    wikidata text,
    doi text,
    crossref text
);

DROP TABLE IF EXISTS openalex.funders_counts_by_year CASCADE;
CREATE TABLE openalex.funders_counts_by_year (
    funder_key bigint,
    year integer,
    works_count integer,
    cited_by_count integer,
    oa_works_count integer
);

DROP TABLE IF EXISTS openalex.funders_roles CASCADE;
CREATE TABLE openalex.funders_roles (
    funder_key bigint,
    role_position integer,
    role text,
    role_id text,
    works_count integer
);

DROP TABLE IF EXISTS openalex.institution_types CASCADE;
CREATE TABLE openalex.institution_types (
    id text,
    display_name text,
    works_count integer,
    cited_by_count integer,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.institutions CASCADE;
CREATE TABLE openalex.institutions (
    institution_key bigint,
    id text,
    ror text,
    display_name text,
    country_code text,
    type text,
    type_id text,
    status text,
    is_super_system boolean,
    works_count integer,
    cited_by_count integer,
    summary_2yr_mean_citedness double precision,
    summary_h_index integer,
    summary_i10_index integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.institutions_ids CASCADE;
CREATE TABLE openalex.institutions_ids (
    institution_key bigint,
    openalex text,
    ror text,
    grid text,
    wikipedia text,
    wikidata text,
    mag text
);

DROP TABLE IF EXISTS openalex.institutions_geo CASCADE;
CREATE TABLE openalex.institutions_geo (
    institution_key bigint,
    city text,
    geonames_city_id text,
    region text,
    country_code text,
    country text,
    latitude double precision,
    longitude double precision
);

DROP TABLE IF EXISTS openalex.institutions_associated_institutions CASCADE;
CREATE TABLE openalex.institutions_associated_institutions (
    institution_key bigint,
    associated_position integer,
    associated_institution_key bigint,
    associated_display_name text,
    relationship text
);

DROP TABLE IF EXISTS openalex.institutions_counts_by_year CASCADE;
CREATE TABLE openalex.institutions_counts_by_year (
    institution_key bigint,
    year integer,
    works_count integer,
    cited_by_count integer,
    oa_works_count integer
);

DROP TABLE IF EXISTS openalex.institutions_roles CASCADE;
CREATE TABLE openalex.institutions_roles (
    institution_key bigint,
    role_position integer,
    role text,
    role_id text,
    works_count integer
);

DROP TABLE IF EXISTS openalex.institutions_repositories CASCADE;
CREATE TABLE openalex.institutions_repositories (
    institution_key bigint,
    repository_position integer,
    repository_id text,
    repository_display_name text,
    host_organization text,
    host_organization_lineage jsonb,
    raw_repository jsonb
);

DROP TABLE IF EXISTS openalex.institutions_topics CASCADE;
CREATE TABLE openalex.institutions_topics (
    institution_key bigint,
    topic_position integer,
    topic_key bigint,
    score double precision,
    count integer,
    subfield_key bigint,
    field_key bigint,
    domain_key bigint
);

DROP TABLE IF EXISTS openalex.institutions_topic_share CASCADE;
CREATE TABLE openalex.institutions_topic_share (
    institution_key bigint,
    topic_position integer,
    topic_key bigint,
    value double precision,
    subfield_key bigint,
    field_key bigint,
    domain_key bigint
);

DROP TABLE IF EXISTS openalex.keywords CASCADE;
CREATE TABLE openalex.keywords (
    id text,
    display_name text,
    works_count integer,
    cited_by_count integer,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.languages CASCADE;
CREATE TABLE openalex.languages (
    id text,
    display_name text,
    works_count integer,
    cited_by_count integer,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.licenses CASCADE;
CREATE TABLE openalex.licenses (
    id text,
    display_name text,
    description text,
    url text,
    works_count integer,
    cited_by_count integer,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.publishers CASCADE;
CREATE TABLE openalex.publishers (
    publisher_key bigint,
    id text,
    display_name text,
    hierarchy_level integer,
    parent_publisher text,
    ror_id text,
    wikidata_id text,
    works_count integer,
    cited_by_count integer,
    summary_2yr_mean_citedness double precision,
    summary_h_index integer,
    summary_i10_index integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.publishers_ids CASCADE;
CREATE TABLE openalex.publishers_ids (
    publisher_key bigint,
    openalex text,
    ror text,
    wikidata text
);

DROP TABLE IF EXISTS openalex.publishers_counts_by_year CASCADE;
CREATE TABLE openalex.publishers_counts_by_year (
    publisher_key bigint,
    year integer,
    works_count integer,
    cited_by_count integer,
    oa_works_count integer
);

DROP TABLE IF EXISTS openalex.publishers_roles CASCADE;
CREATE TABLE openalex.publishers_roles (
    publisher_key bigint,
    role_position integer,
    role text,
    role_id text,
    works_count integer
);

DROP TABLE IF EXISTS openalex.sdgs CASCADE;
CREATE TABLE openalex.sdgs (
    id text,
    display_name text,
    description text,
    image_url text,
    image_thumbnail_url text,
    works_count integer,
    cited_by_count integer,
    ids jsonb,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.source_types CASCADE;
CREATE TABLE openalex.source_types (
    id text,
    display_name text,
    works_count integer,
    cited_by_count integer,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.sources CASCADE;
CREATE TABLE openalex.sources (
    source_key bigint,
    id text,
    issn_l text,
    issn jsonb,
    display_name text,
    country_code text,
    type text,
    publisher text,
    host_organization text,
    host_organization_name text,
    works_count integer,
    cited_by_count integer,
    oa_works_count integer,
    is_oa boolean,
    is_in_doaj boolean,
    is_core boolean,
    is_ojs boolean,
    is_in_scielo boolean,
    is_high_oa_rate boolean,
    is_high_oa_rate_since_year integer,
    is_in_doaj_since_year integer,
    first_publication_year integer,
    last_publication_year integer,
    oa_flip_year integer,
    apc_usd integer,
    summary_2yr_mean_citedness double precision,
    summary_h_index integer,
    summary_i10_index integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.sources_ids CASCADE;
CREATE TABLE openalex.sources_ids (
    source_key bigint,
    openalex text,
    issn_l text,
    issn jsonb,
    mag text,
    wikidata text,
    fatcat text
);

DROP TABLE IF EXISTS openalex.sources_counts_by_year CASCADE;
CREATE TABLE openalex.sources_counts_by_year (
    source_key bigint,
    year integer,
    works_count integer,
    cited_by_count integer,
    oa_works_count integer
);

DROP TABLE IF EXISTS openalex.sources_apc_prices CASCADE;
CREATE TABLE openalex.sources_apc_prices (
    source_key bigint,
    price_position integer,
    price integer,
    currency text
);

DROP TABLE IF EXISTS openalex.sources_topics CASCADE;
CREATE TABLE openalex.sources_topics (
    source_key bigint,
    topic_position integer,
    topic_key bigint,
    score double precision,
    count integer,
    subfield_key bigint,
    field_key bigint,
    domain_key bigint
);

DROP TABLE IF EXISTS openalex.sources_topic_share CASCADE;
CREATE TABLE openalex.sources_topic_share (
    source_key bigint,
    topic_position integer,
    topic_key bigint,
    value double precision,
    subfield_key bigint,
    field_key bigint,
    domain_key bigint
);

DROP TABLE IF EXISTS openalex.subfields CASCADE;
CREATE TABLE openalex.subfields (
    subfield_key bigint,
    id text,
    display_name text,
    description text,
    field_key bigint,
    field_display_name text,
    domain_key bigint,
    domain_display_name text,
    works_count integer,
    cited_by_count integer,
    display_name_alternatives jsonb,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.subfields_ids CASCADE;
CREATE TABLE openalex.subfields_ids (
    subfield_key bigint,
    openalex text,
    wikidata text,
    wikipedia text
);

DROP TABLE IF EXISTS openalex.subfields_topics CASCADE;
CREATE TABLE openalex.subfields_topics (
    subfield_key bigint,
    topic_position integer,
    topic_key bigint,
    topic_display_name text
);

DROP TABLE IF EXISTS openalex.subfields_siblings CASCADE;
CREATE TABLE openalex.subfields_siblings (
    subfield_key bigint,
    sibling_position integer,
    sibling_id text,
    sibling_display_name text
);

DROP TABLE IF EXISTS openalex.topics CASCADE;
CREATE TABLE openalex.topics (
    topic_key bigint,
    id text,
    display_name text,
    subfield_key bigint,
    subfield_display_name text,
    field_key bigint,
    field_display_name text,
    domain_key bigint,
    domain_display_name text,
    works_count integer,
    cited_by_count integer,
    wikipedia_id text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.topics_ids CASCADE;
CREATE TABLE openalex.topics_ids (
    topic_key bigint,
    openalex text,
    wikipedia text
);

DROP TABLE IF EXISTS openalex.topics_keywords CASCADE;
CREATE TABLE openalex.topics_keywords (
    topic_key bigint,
    keyword_position integer,
    keyword text
);

DROP TABLE IF EXISTS openalex.topics_siblings CASCADE;
CREATE TABLE openalex.topics_siblings (
    topic_key bigint,
    sibling_position integer,
    sibling_id text,
    sibling_display_name text
);

DROP TABLE IF EXISTS openalex.work_types CASCADE;
CREATE TABLE openalex.work_types (
    id text,
    display_name text,
    description text,
    works_count integer,
    cited_by_count integer,
    works_api_url text,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.works CASCADE;
CREATE TABLE openalex.works (
    work_key bigint,
    id text,
    doi text,
    title text,
    publication_year integer,
    publication_date date,
    language text,
    type text,
    authors_count integer,
    cited_by_count integer,
    referenced_works_count integer,
    locations_count integer,
    countries_distinct_count integer,
    institutions_distinct_count integer,
    fwci double precision,
    is_retracted boolean,
    is_paratext boolean,
    is_xpac boolean,
    has_fulltext boolean,
    has_content_pdf boolean,
    has_content_grobid_xml boolean,
    primary_topic_key bigint,
    primary_topic_score double precision,
    primary_topic_subfield_key bigint,
    primary_topic_field_key bigint,
    primary_topic_domain_key bigint,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
);

DROP TABLE IF EXISTS openalex.works_ids CASCADE;
CREATE TABLE openalex.works_ids (
    work_key bigint,
    openalex text,
    doi text,
    mag text,
    pmid text,
    pmcid text
);

DROP TABLE IF EXISTS openalex.works_indexed_in CASCADE;
CREATE TABLE openalex.works_indexed_in (
    work_key bigint,
    position integer,
    indexed_in text
);

DROP TABLE IF EXISTS openalex.works_corresponding_author_ids CASCADE;
CREATE TABLE openalex.works_corresponding_author_ids (
    work_key bigint,
    position integer,
    author_key bigint
);

DROP TABLE IF EXISTS openalex.works_corresponding_institution_ids CASCADE;
CREATE TABLE openalex.works_corresponding_institution_ids (
    work_key bigint,
    position integer,
    institution_key bigint
);

DROP TABLE IF EXISTS openalex.works_primary_locations CASCADE;
CREATE TABLE openalex.works_primary_locations (
    work_key bigint,
    location_position integer,
    location_id text,
    source_key bigint,
    is_oa boolean,
    is_published boolean,
    is_accepted boolean,
    landing_page_url text,
    pdf_url text,
    license text,
    license_id text,
    version text
);

DROP TABLE IF EXISTS openalex.works_locations CASCADE;
CREATE TABLE openalex.works_locations (
    work_key bigint,
    location_position integer,
    location_id text,
    source_key bigint,
    is_oa boolean,
    is_published boolean,
    is_accepted boolean,
    landing_page_url text,
    pdf_url text,
    license text,
    license_id text,
    version text
);

DROP TABLE IF EXISTS openalex.works_best_oa_locations CASCADE;
CREATE TABLE openalex.works_best_oa_locations (
    work_key bigint,
    location_position integer,
    location_id text,
    source_key bigint,
    is_oa boolean,
    is_published boolean,
    is_accepted boolean,
    landing_page_url text,
    pdf_url text,
    license text,
    license_id text,
    version text
);

DROP TABLE IF EXISTS openalex.works_authorships CASCADE;
CREATE TABLE openalex.works_authorships (
    work_key bigint,
    authorship_position integer,
    author_position text,
    author_key bigint,
    author_display_name text,
    raw_author_name text,
    is_corresponding boolean
);

DROP TABLE IF EXISTS openalex.works_authorship_institutions CASCADE;
CREATE TABLE openalex.works_authorship_institutions (
    work_key bigint,
    authorship_position integer,
    institution_position integer,
    author_key bigint,
    institution_key bigint,
    institution_country_code text
);

DROP TABLE IF EXISTS openalex.works_authorship_countries CASCADE;
CREATE TABLE openalex.works_authorship_countries (
    work_key bigint,
    authorship_position integer,
    country_position integer,
    country_code text
);

DROP TABLE IF EXISTS openalex.works_biblio CASCADE;
CREATE TABLE openalex.works_biblio (
    work_key bigint,
    volume text,
    issue text,
    first_page text,
    last_page text
);

DROP TABLE IF EXISTS openalex.works_topics CASCADE;
CREATE TABLE openalex.works_topics (
    work_key bigint,
    topic_position integer,
    topic_key bigint,
    score double precision
);

DROP TABLE IF EXISTS openalex.works_funders CASCADE;
CREATE TABLE openalex.works_funders (
    work_key bigint,
    funder_position integer,
    funder_key bigint
);

DROP TABLE IF EXISTS openalex.works_institutions CASCADE;
CREATE TABLE openalex.works_institutions (
    work_key bigint,
    institution_position integer,
    institution_key bigint,
    institution_country_code text
);

DROP TABLE IF EXISTS openalex.works_open_access CASCADE;
CREATE TABLE openalex.works_open_access (
    work_key bigint,
    is_oa boolean,
    oa_status text,
    oa_url text,
    any_repository_has_fulltext boolean
);

DROP TABLE IF EXISTS openalex.works_counts_by_year CASCADE;
CREATE TABLE openalex.works_counts_by_year (
    work_key bigint,
    year integer,
    cited_by_count integer
);

DROP TABLE IF EXISTS openalex.works_citation_normalized_percentile CASCADE;
CREATE TABLE openalex.works_citation_normalized_percentile (
    work_key bigint,
    value double precision,
    is_in_top_1_percent boolean,
    is_in_top_10_percent boolean
);

DROP TABLE IF EXISTS openalex.works_cited_by_percentile_year CASCADE;
CREATE TABLE openalex.works_cited_by_percentile_year (
    work_key bigint,
    min integer,
    max integer
);

DROP TABLE IF EXISTS openalex.works_apc_list CASCADE;
CREATE TABLE openalex.works_apc_list (
    work_key bigint,
    value double precision,
    currency text,
    value_usd double precision,
    provenance text
);

DROP TABLE IF EXISTS openalex.works_apc_paid CASCADE;
CREATE TABLE openalex.works_apc_paid (
    work_key bigint,
    value double precision,
    currency text,
    value_usd double precision,
    provenance text
);
